# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42d46c472519872062947aee90f8722c9795d55e7958eaa92782e3335e85b6cd2e42729c59e298f3432c7b3670dad5f691d513c6106a088dd0e6a0ff7dddd80d

test:
  secret_key_base: 60a6a692b716e7896a1b72607912d32517585c784b248ee87ffc49fba17880e551768eae3431dfe36e609dc93ed8237c8f6dafecddbb462814333e019ef39497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
